# Generated by Django 5.1 on 2024-08-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.URLField(max_length=500)),
                ('state', models.CharField(max_length=2)),
                ('cost_per_kwh', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_kwh_limit', models.PositiveIntegerField()),
                ('total_clients', models.PositiveIntegerField()),
                ('average_rating', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
