# Generated by Django 5.1 on 2024-08-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='state',
            field=models.CharField(max_length=255),
        ),
    ]
